/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class apiratehat_androidsamplecode_jni_NDKTools */

#ifndef _Included_apiratehat_androidsamplecode_jni_NDKTools
#define _Included_apiratehat_androidsamplecode_jni_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     apiratehat_androidsamplecode_jni_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_apiratehat_androidsamplecode_jni_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
